spring.application.name=Todolist
spring.datasource.url=jdbc:postgresql://localhost:5432/todolist
spring.datasource.username=postgres
spring.datasource.password=Sanjay2002
spring.jpa.hibernate.ddl-auto=update